# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staging

on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Build project 
      run: |
        npm ci
        npm run build --if-present

    - name: Install Firebase
      env: 
        FIREBASE_TOKEN:  ${{secrets.FIREBASE_TOKEN}}
      run : |
         sudo npm install -g firebase-tools
         firebase target:apply hosting staging staging-sample-firebase-github
         firebase deploy --token $FIREBASE_TOKEN --only hosting:staging --non-interactive
      if: github.even_name=='push'
    
    - name: Bump version
      run: |
        git config --global user.email "version@email.com"
        git config --global user.ame "Version Bumping"
        npm version patch
        git push
      if: github.event_name=='push'
      
         
